### ISSUE TITLE
Continuous joints not supported (silently)

### ISSUE THREAD

**Issue by henningkayser** [PickNikRobotics/pick_ik#57]
When running pick_ik with robot models that have continuous (as unbounded) joints, pick_ik will fail to produce solutions reliably.

Reason: [get_random_valid_configuration()](https://github.com/PickNikRobotics/pick_ik/blob/main/src/robot.cpp#L73) will sample states that have `inf` for joint values, since bounds are set to the numeric limits which the distribution sampler doesn't support

Behavior: FK will silently add `nan`, `inf`, or 0 to transforms which in turn fail to compute any useful distance metrics.

We should either check for these cases and warn, or implement a random sampler that supports infinite (or numeric limits) bounds.

**Comment by sea-bass** [comment]
Oof, nice catch!

What do you think of continuous joints being handled as sampled from 0 to 2*pi radians, and once a solution is achieved snapping it to the closest multiple of 2*pi to its initial seed?

**Comment by MarqRazz** [comment]
FYI the continuous joints on the Kinova are -pi to pi so you might want to decrease the range.

**Comment by MarqRazz** [comment]
@sea-bass what version of Studio are you targeting? Could you please update the milestone?

**Comment by sea-bass** [comment]
Not necessary to get this in anytime soon since we punted on `pick_ik` -- can't add a milestone since this PR is not in the Studio repo.
