### ISSUE TITLE
Error running test executable while building

### ISSUE THREAD

**Issue by kakandikonda** [PickNikRobotics/pick_ik#64]
Hello,

I am getting this problem when building Moveit2 with ROS2 Iron. I saw a similar issue as well but since our issues were slightly different I thought I'd make a different post. I attached a screenshot of my error output below. 

![Screenshot from 2023-11-17 12-50-52](https://github.com/PickNikRobotics/pick_ik/assets/34494222/2948e482-ca6d-44e6-a8aa-409a62e645d1)

**Comment by sea-bass** [comment]
Did you by any chance have build output from a former version, or anything like that in your workspace? If you rebulid the `pick_ik` package as follows, does the issue still persist?

```
cd <YOUR WORKSPACE>
rm -rf build/pick_ik install/pick_ik
colcon build
```

**Comment by kakandikonda** [comment]
Yes, I just tried it and was getting the same error as above. I also tried redoing the whole process but that didn't work either.

**Comment by sea-bass** [comment]
I was able to reproduce this only if I also had binaries for `pick_ik` installed. Can you try

```
sudo apt-get remove ros-rolling-pick-ik
```

**Comment by sea-bass** [comment]
Confirmed in #65 that this resolves the issue.
